In [1]:
import numpy as np 

In [2]:
x = np.array([
    [ 3 , 4 , 5],
    [ 2 , 8 , 9]
])

print(x.shape)

(2, 3)


In [3]:
y = np.array([
    [ 1 , 2 , 3]
])

print(y.shape)

(1, 3)


In [4]:
z = np.eye(5)

print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# To select part of array ( one colomn , one row , multi colomn , multi row , sub array )
n = np.array([
    [ 3 , 4 , 9 ],
    [ 1 , 0 , 7 ],
    [ 5 , 2 , 1 ]
])

print(n[0:2,1:3])

[[4 9]
 [0 7]]


In [7]:
# To print matrix all element have zero .
m = np.zeros((3,3))

print(m)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [59]:
# To make condion in array any show specific element
mask = ( n > 5 )

print(mask)
print(n[mask])

[[False False  True]
 [False False  True]
 [False False False]]
[9 7]


In [9]:
print(n[ n > 5 ])

[9 7]


In [10]:
# To transpose the array.
n = np.array([
    [ 3 , 4 , 9 ],
    [ 1 , 0 , 7 ],
    [ 5 , 2 , 1 ]
])

print(n.T)

[[3 1 5]
 [4 0 2]
 [9 7 1]]


In [11]:
# To show array in one dimention
n = np.array([
    [ 3 , 4 , 9 , 2],
    [ 1 , 0 , 7 , 1],
    [ 5 , 2 , 1 , 7]
])

print(n.reshape(2,6))

[[3 4 9 2 1 0]
 [7 1 5 2 1 7]]


In [12]:
n = np.array([
    [ 3 , 4 , 9 ],
    [ 1 , 0 , 7 ],
    [ 5 , 2 , 1 ]
])

print(n.reshape(1,9)) #Two dimension
print()
print(n.reshape(-1)) #One dimension

[[3 4 9 1 0 7 5 2 1]]

[3 4 9 1 0 7 5 2 1]


In [13]:
n = np.array([
    [ 3 , 4 , 9 ],
    [ 1 , 0 , 7 ],
    [ 5 , 2 , 1 ]
])

print(n.flatten()) 
print()             # Or ( To show array in one dimention )
print(n.reshape(-1)) 

[3 4 9 1 0 7 5 2 1]

[3 4 9 1 0 7 5 2 1]


In [14]:
# To show one Row in the shap of row.
o = np.array([
    [ 4 , 3 , 6 , 9 ],
    [ 1 , 2 , 8 , 7 ],
    [ 6 , 4 , 5 , 2 ]
])

print(o[:,1].reshape( -1 , 1 ))

[[3]
 [2]
 [4]]


In [15]:
x = np.array([
    [ 1 , 2 , 3 ],
    [ 4 , 5 , 6 ]
])

y = np.array([
    [ 4 , 3 , 6 , 9 ],
    [ 1 , 2 , 8 , 7 ],
    [ 6 , 4 , 5 , 2 ]
])

z = np.dot( x , y )    # To make multiple between two matrix .

print(z)
print()
print(x.shape)
print(y.shape)
print()
print(z.shape)

[[24 19 37 29]
 [57 46 94 83]]

(2, 3)
(3, 4)

(2, 4)


In [16]:
x = np.array([
    [ 1 , 2 , 3 ],
    [ 4 , 5 , 6 ]
])

print(x.sum( axis = 0 , keepdims = True )) # 0 ==> To sum row , 1 ==> To sum column 
                                           # keepdims To keep array in dimention one or two D

[[5 7 9]]


In [17]:
# To make log ==> ( log(x) , log2(x) , log10(x) )
x = np.array([
    [ 1 , 2 , 3 ],
    [ 4 , 5 , 6 ]
])

print(np.log2(x))

[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]


In [18]:
# To make exp 
x = np.array([
    [ 1 , 2 , 3 ],
    [ 4 , 5 , 6 ]
])

print(np.exp(x))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [19]:
a = np.sin(30*np.pi/180)
b = np.cos(30*np.pi/180)
c = np.tan(30*np.pi/180)

print(a)
print(b)
print(c)

0.49999999999999994
0.8660254037844387
0.5773502691896257


In [20]:
a = round(3.789)
b = round(2.134,1)
c = round(5.284,2)

print(a)
print(b)
print(c)

4
2.1
5.28


In [23]:
a = [[1,2,3],[5,3,6],[9,6,5]]
b = np.array(a)

print(a)
print()
print(b)

[[1, 2, 3], [5, 3, 6], [9, 6, 5]]

[[1 2 3]
 [5 3 6]
 [9 6 5]]


In [27]:
# i+2 ==> the number of column and [2,4,6] ==> number of rows and start number of row .
a = np.array([range( i , i + 3 )for i in [2,4,6]])

print(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [30]:
# Random matrix from 0 to 1.
a = np.random.rand(5,3)
b = np.random.rand(2,3,3)

print(a)
print()
print(b)

[[0.57496605 0.81157396 0.87997417]
 [0.01566086 0.5495121  0.28163065]
 [0.78238026 0.94543452 0.79967069]
 [0.2614328  0.72348145 0.80974576]
 [0.00694131 0.21225524 0.59797628]]

[[[0.36722034 0.402872   0.36579358]
  [0.85136544 0.98100316 0.49855064]
  [0.78145359 0.33260024 0.36941914]]

 [[0.00935747 0.81455701 0.63378192]
  [0.22624336 0.91862115 0.33860322]
  [0.66313916 0.70250504 0.74169247]]]


In [37]:
# Random intger number .( randint(startint , endint , the random number need))
a = np.random.randint(0,10,5)
b = np.random.randint(1,25,4)

print(a)
print(b)
print(b.reshape(2,2))

[5 1 0 0 6]
[21  1  4 17]
[[21  1]
 [ 4 17]]


In [49]:
# shuffle(array_of_number) to random set of number . ==> use in data set to be part in testing and part in traning.
x = [1,2,3,4,5,6,7,8,9,0]
print(x)

np.random.shuffle(x)
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[5, 7, 8, 6, 3, 1, 0, 9, 2, 4]


In [54]:
# choice(array_of_number) to choice random int from array.
y = [3,4,2,7,1,0,8]
a = np.random.choice(y)
b = np.random.choice(y, size = 3)

print(a)
print(b)

8
[3 8 0]


In [56]:
# To seperate between two number .
a = np.linspace(1,30)
b = np.linspace(0,100,5)

print(a)
print(b)

[ 1.          1.59183673  2.18367347  2.7755102   3.36734694  3.95918367
  4.55102041  5.14285714  5.73469388  6.32653061  6.91836735  7.51020408
  8.10204082  8.69387755  9.28571429  9.87755102 10.46938776 11.06122449
 11.65306122 12.24489796 12.83673469 13.42857143 14.02040816 14.6122449
 15.20408163 15.79591837 16.3877551  16.97959184 17.57142857 18.16326531
 18.75510204 19.34693878 19.93877551 20.53061224 21.12244898 21.71428571
 22.30612245 22.89795918 23.48979592 24.08163265 24.67346939 25.26530612
 25.85714286 26.44897959 27.04081633 27.63265306 28.2244898  28.81632653
 29.40816327 30.        ]
[  0.  25.  50.  75. 100.]


In [58]:
# Diagonal matrix . k ==> (number of extra rows and columns)
a = np.diag(np.array([1,2,3,4,5]))
b = np.diag(np.array([1,2,3,4,5]), k = 3)

print(a)
print()
print(b)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

[[0 0 0 1 0 0 0 0]
 [0 0 0 0 2 0 0 0]
 [0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 5]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [64]:
x = np.random.randint(1,10,9).reshape(3,3)
y = np.count_nonzero(x)
z = np.count_nonzero(x > 5 , axis = 1 )

print(x)
print()
print(y)
print()
print(z)

[[8 2 2]
 [9 7 7]
 [2 7 3]]

9

[1 3 1]
